# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'iOSDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'WebViewJavascriptBridge', '~> 6.0'
  pod 'YYModel', '~> 1.0.4'
  pod 'SVProgressHUD', '~> 2.1.2'
  pod 'SDWebImage'
  

end
